// Catalogo di TUTTI i campi della tabella agencies con documentazione
// operativa: descrizione, sorgente, policy di aggiornamento, comportamento
// verso agenzie verificate, visibilità pubblica, mappature CSV.
//
// Fonte di verità: leggere questo file per capire come si comporta un campo.
// Se cambi il codice degli agenti/route, aggiorna qui.

export type FieldCategory =
  | "Identità"
  | "Media"
  | "Sedi"
  | "Mercati"
  | "Contatti"
  | "Social"
  | "Servizi"
  | "Clienti & fit"
  | "Pricing"
  | "Contenuti"
  | "Recensioni"
  | "Prove"
  | "Valutazione"
  | "Financial"
  | "SEO"
  | "Workflow"
  | "Commerciale"
  | "Enrichment tracking"
  | "Sistema";

export type FieldSource =
  | "google_places" // Google Places API
  | "llm" // Estrazione LLM dal sito
  | "geo_resolver" // Parser indirizzo → città/regione
  | "visual_agent" // agency-visual-enrichment (logo/photos/portfolio)
  | "manual" // Editor umano dashboard
  | "partner" // Dato fornito da partner esterno (registro imprese, cerved, ecc.)
  | "computed" // Calcolato lato server da altri campi
  | "creation" // Impostato all'insert, mai aggiornato
  | "system"; // Timestamp/UUID automatici

export type UpdatePolicy =
  | "always_overwrite" // L'agente scrive sempre, sovrascrive valore esistente
  | "fill_if_empty" // L'agente scrive solo se DB è null/vuoto (rispetta curatela)
  | "manual_only" // Solo editor umano
  | "on_creation" // Settato all'insert, mai toccato dopo
  | "computed_per_run"; // Ricalcolato ad ogni run/read

export type Visibility = "pubblico" | "interno" | "pubblico_opzionale";

export interface FieldDefinition {
  key: string; // colonna DB
  label: string; // nome umano
  category: FieldCategory;
  type: string; // text | text[] | int | numeric | boolean | date | timestamptz | jsonb | uuid
  description: string;
  source: FieldSource;
  updatePolicy: UpdatePolicy;
  verifiedBehavior: string; // Cosa succede se l'agenzia è verificata
  visibility: Visibility;
  csvV1?: string; // Colonna nel CSV /api/export/agencies.csv (WP All Import oggi)
  csvV2?: string; // Colonna nel CSV /api/export/agencies-v2.csv (dizionario)
  notes?: string;
}

// Frase riutilizzabile per i campi con policy fill_if_empty (già protetti
// dall'agente indipendentemente dal flag "verified": bastano dei valori
// presenti in DB perché l'agente non li tocchi).
const V_FILL = "L'agente scrive solo se il campo è vuoto — la curatela manuale è già protetta a prescindere dal flag verified.";
const V_OW = "L'agente sovrascrive sempre. Il flag verified oggi NON blocca la sovrascrittura.";
const V_NEVER = "Non toccato da nessun agente automatico.";
const V_VISUAL = "Sovrascritto dal visual agent quando trova un candidato con confidence ≥ soglia.";
const V_SYSTEM = "Aggiornato automaticamente ad ogni operazione.";

export const FIELDS_CATALOG: FieldDefinition[] = [
  // ============================================================
  // IDENTITÀ
  // ============================================================
  {
    key: "id",
    label: "Agency ID",
    category: "Sistema",
    type: "uuid",
    description: "Identificatore stabile dell'agenzia. Chiave primaria interna.",
    source: "system",
    updatePolicy: "on_creation",
    verifiedBehavior: V_NEVER,
    visibility: "interno",
  },
  {
    key: "wp_id",
    label: "WordPress ID",
    category: "Sistema",
    type: "int",
    description: "ID legacy WordPress per re-import incrementale (upsert). NULL per agenzie create dal brain.",
    source: "creation",
    updatePolicy: "on_creation",
    verifiedBehavior: V_NEVER,
    visibility: "interno",
    csvV1: "ID",
  },
  {
    key: "slug",
    label: "Slug",
    category: "Identità",
    type: "text",
    description: "Slug pubblico univoco della scheda agenzia. Generato dal title alla creazione.",
    source: "creation",
    updatePolicy: "on_creation",
    verifiedBehavior: V_NEVER,
    visibility: "pubblico",
    csvV2: "slug",
    notes: "Cambiarlo rompe URL pubblici — usare redirect.",
  },
  {
    key: "title",
    label: "Nome agenzia",
    category: "Identità",
    type: "text",
    description: "Nome pubblico dell'agenzia. Impostato alla creazione o import CSV.",
    source: "manual",
    updatePolicy: "manual_only",
    verifiedBehavior: V_NEVER,
    visibility: "pubblico",
    csvV1: "Title",
    csvV2: "display_name",
  },
  {
    key: "title_originale",
    label: "Title originale",
    category: "Identità",
    type: "text",
    description: "Valore del title prima di eventuali normalizzazioni.",
    source: "creation",
    updatePolicy: "on_creation",
    verifiedBehavior: V_NEVER,
    visibility: "interno",
    csvV1: "Title originale",
    csvV2: "alternate_names",
    notes: "Nel v2 viene combinato con alternate_names.",
  },
  {
    key: "parent_slug",
    label: "Parent slug",
    category: "Identità",
    type: "text",
    description: "Slug dell'agenzia/gruppo proprietario di questo brand.",
    source: "manual",
    updatePolicy: "manual_only",
    verifiedBehavior: V_NEVER,
    visibility: "pubblico",
    csvV1: "Parent slug",
    csvV2: "parent_slug",
  },
  {
    key: "alternate_names",
    label: "Alternate names",
    category: "Identità",
    type: "text[]",
    description: "Varianti del nome (acronimi, sigle, brand alternativi). Max 3.",
    source: "llm",
    updatePolicy: "fill_if_empty",
    verifiedBehavior: V_FILL,
    visibility: "pubblico",
    csvV1: "Alternate names",
    csvV2: "alternate_names",
  },
  {
    key: "partita_iva",
    label: "Partita IVA",
    category: "Identità",
    type: "text",
    description: "P.IVA italiana (11 cifre). Estratta dal sito se presente.",
    source: "llm",
    updatePolicy: "fill_if_empty",
    verifiedBehavior: V_FILL,
    visibility: "pubblico",
    csvV1: "Partita IVA",
    csvV2: "vat_id",
    notes: "Ignora CF (16 char) e REA.",
  },
  {
    key: "anno_di_fondazione",
    label: "Anno di fondazione",
    category: "Identità",
    type: "int",
    description: "Anno di fondazione del brand.",
    source: "llm",
    updatePolicy: "fill_if_empty",
    verifiedBehavior: V_FILL,
    visibility: "pubblico",
    csvV1: "Anno di fondazione",
    csvV2: "founding_year",
    notes: "Accetta solo se citato esplicitamente ('fondata nel 2015').",
  },
  {
    key: "incorporation_year",
    label: "Anno costituzione società",
    category: "Identità",
    type: "int",
    description: "Anno di costituzione della società (registro imprese). Distinto dal founding_year.",
    source: "partner",
    updatePolicy: "manual_only",
    verifiedBehavior: V_NEVER,
    visibility: "pubblico",
    csvV1: "Incorporation year",
    csvV2: "incorporation_year",
  },
  {
    key: "legal_form",
    label: "Forma giuridica",
    category: "Identità",
    type: "text",
    description: "Forma giuridica della società (Srl, Spa, Snc, ecc).",
    source: "partner",
    updatePolicy: "manual_only",
    verifiedBehavior: V_NEVER,
    visibility: "pubblico",
    csvV1: "Legal form",
    csvV2: "legal_form",
  },
  {
    key: "founder_leader",
    label: "Founder & leader",
    category: "Identità",
    type: "jsonb",
    description: "Array {name, role} di founder/CEO/leader citati esplicitamente sul sito. Max 5.",
    source: "llm",
    updatePolicy: "fill_if_empty",
    verifiedBehavior: V_FILL,
    visibility: "pubblico",
    csvV1: "Founder leader JSON",
    csvV2: "founder_leader_json",
  },

  // ============================================================
  // MEDIA
  // ============================================================
  {
    key: "logo_url",
    label: "Logo URL",
    category: "Media",
    type: "text",
    description: "URL pubblico del logo su Supabase Storage.",
    source: "visual_agent",
    updatePolicy: "always_overwrite",
    verifiedBehavior: V_VISUAL,
    visibility: "pubblico",
    csvV2: "logo_url",
  },
  {
    key: "logo_meta",
    label: "Logo metadata",
    category: "Media",
    type: "jsonb",
    description: "Metadati del logo: file_name, mime, dimensioni, alt_text, source_url, confidence.",
    source: "visual_agent",
    updatePolicy: "always_overwrite",
    verifiedBehavior: V_VISUAL,
    visibility: "interno",
  },
  {
    key: "foto_del_team",
    label: "Foto team (legacy)",
    category: "Media",
    type: "text",
    description: "Singola URL foto team importata da WP. Legacy — sostituito da `photos` jsonb.",
    source: "creation",
    updatePolicy: "on_creation",
    verifiedBehavior: V_NEVER,
    visibility: "pubblico",
    csvV1: "Foto del team",
    csvV2: "team_photo_url",
  },
  {
    key: "photos",
    label: "Foto team (jsonb)",
    category: "Media",
    type: "jsonb",
    description: "Array oggetti foto team con public_url, dimensioni, alt_text, team_confidence, source_url. Max 3.",
    source: "visual_agent",
    updatePolicy: "always_overwrite",
    verifiedBehavior: "Il visual agent appende nuove foto trovate (dedup su source_url) ma non rimuove le esistenti.",
    visibility: "pubblico",
  },
  {
    key: "portfolio",
    label: "Portfolio images",
    category: "Media",
    type: "jsonb",
    description: "Array oggetti portfolio/case images con public_url, dimensioni, portfolio_confidence. Max 6.",
    source: "visual_agent",
    updatePolicy: "always_overwrite",
    verifiedBehavior: "Il visual agent appende nuove immagini trovate (dedup su source_url).",
    visibility: "pubblico",
    csvV1: "Portfolio JSON",
    csvV2: "portfolio_json",
  },
  {
    key: "case_studies",
    label: "Case studies (legacy)",
    category: "Prove",
    type: "jsonb",
    description: "Array oggetti case study importati da WP. Non aggiornato automaticamente.",
    source: "creation",
    updatePolicy: "on_creation",
    verifiedBehavior: V_NEVER,
    visibility: "pubblico",
    csvV2: "top_cases_json",
  },
  {
    key: "google_partner_cert",
    label: "Google Partner cert",
    category: "Identità",
    type: "boolean",
    description: "Flag: agenzia certificata Google Partner. Manuale.",
    source: "manual",
    updatePolicy: "manual_only",
    verifiedBehavior: V_NEVER,
    visibility: "pubblico",
  },

  // ============================================================
  // SEDI (attualmente flat, una sola sede in agencies)
  // ============================================================
  {
    key: "indirizzo_completo",
    label: "Indirizzo completo",
    category: "Sedi",
    type: "text",
    description: "Indirizzo completo dichiarato sul sito (multiline).",
    source: "llm",
    updatePolicy: "fill_if_empty",
    verifiedBehavior: V_FILL,
    visibility: "pubblico",
    csvV1: "Indirizzo completo",
    csvV2: "main_street",
  },
  {
    key: "google_indirizzo",
    label: "Indirizzo Google",
    category: "Sedi",
    type: "text",
    description: "formattedAddress restituito da Google Places (autorità).",
    source: "google_places",
    updatePolicy: "always_overwrite",
    verifiedBehavior: V_OW,
    visibility: "pubblico",
    csvV1: "Indirizzo Google",
    csvV2: "main_street",
    notes: "Preferito rispetto a indirizzo_completo se presente.",
  },
  {
    key: "citta",
    label: "Città",
    category: "Sedi",
    type: "text",
    description: "Slug città (es. 'milano') derivato dal parser geo su google_indirizzo o indirizzo LLM.",
    source: "geo_resolver",
    updatePolicy: "always_overwrite",
    verifiedBehavior: V_OW,
    visibility: "pubblico",
    csvV1: "Città",
    csvV2: "main_locality",
    notes: "SEMPRE sovrascritto: le aree WP legacy erano spesso sbagliate.",
  },
  {
    key: "regioni",
    label: "Regione",
    category: "Sedi",
    type: "text",
    description: "Slug regione (es. 'lombardia') derivato dal parser geo.",
    source: "geo_resolver",
    updatePolicy: "always_overwrite",
    verifiedBehavior: V_OW,
    visibility: "pubblico",
    csvV1: "Regioni",
    csvV2: "main_region",
  },

  // ============================================================
  // MERCATI
  // ============================================================
  {
    key: "aree",
    label: "Aree",
    category: "Mercati",
    type: "text",
    description: "Formato 'Regione>Città'. Derivato dal parser geo.",
    source: "geo_resolver",
    updatePolicy: "always_overwrite",
    verifiedBehavior: V_OW,
    visibility: "pubblico",
    csvV1: "Aree",
    csvV2: "areas_served",
  },

  // ============================================================
  // CONTATTI
  // ============================================================
  {
    key: "email",
    label: "Email pubblica",
    category: "Contatti",
    type: "text",
    description: "Email di contatto pubblica estratta dal sito.",
    source: "llm",
    updatePolicy: "fill_if_empty",
    verifiedBehavior: V_FILL,
    visibility: "pubblico",
    csvV1: "Email",
    csvV2: "public_email",
  },
  {
    key: "telefono",
    label: "Telefono",
    category: "Contatti",
    type: "text",
    description: "Numero di telefono dal sito.",
    source: "llm",
    updatePolicy: "fill_if_empty",
    verifiedBehavior: V_FILL,
    visibility: "pubblico",
    csvV1: "Telefono",
    csvV2: "public_phone",
  },
  {
    key: "google_telefono",
    label: "Telefono Google",
    category: "Contatti",
    type: "text",
    description: "Telefono restituito da Google Places (autorità).",
    source: "google_places",
    updatePolicy: "always_overwrite",
    verifiedBehavior: V_OW,
    visibility: "pubblico",
    csvV1: "Telefono Google",
    csvV2: "public_phone",
    notes: "Preferito rispetto a telefono LLM se presente.",
  },
  {
    key: "google_sito",
    label: "Sito Google",
    category: "Contatti",
    type: "text",
    description: "websiteUri restituito da Google Places.",
    source: "google_places",
    updatePolicy: "always_overwrite",
    verifiedBehavior: V_OW,
    visibility: "pubblico",
    csvV1: "Sito Google",
  },
  {
    key: "sito_web",
    label: "Sito web",
    category: "Contatti",
    type: "text",
    description: "URL sito ufficiale dell'agenzia. Chiave per lo scraping e Google Places domain-match.",
    source: "manual",
    updatePolicy: "manual_only",
    verifiedBehavior: V_NEVER,
    visibility: "pubblico",
    csvV1: "Sito web",
    csvV2: "canonical_website",
  },

  // ============================================================
  // SOCIAL
  // ============================================================
  {
    key: "linkedin",
    label: "LinkedIn URL",
    category: "Social",
    type: "text",
    description: "URL LinkedIn aziendale.",
    source: "llm",
    updatePolicy: "fill_if_empty",
    verifiedBehavior: V_FILL,
    visibility: "pubblico",
    csvV1: "LinkedIn",
    csvV2: "linkedin_url",
  },
  {
    key: "instagram",
    label: "Instagram URL",
    category: "Social",
    type: "text",
    description: "URL Instagram.",
    source: "llm",
    updatePolicy: "fill_if_empty",
    verifiedBehavior: V_FILL,
    visibility: "pubblico",
    csvV1: "Instagram",
    csvV2: "instagram_url",
  },
  {
    key: "behance",
    label: "Behance URL",
    category: "Social",
    type: "text",
    description: "URL Behance.",
    source: "llm",
    updatePolicy: "fill_if_empty",
    verifiedBehavior: V_FILL,
    visibility: "pubblico",
    csvV1: "Behance",
    csvV2: "behance_url",
  },

  // ============================================================
  // SERVIZI (competenze legacy + tassonomie dictionary)
  // ============================================================
  {
    key: "competenze_core",
    label: "Servizi core",
    category: "Servizi",
    type: "text[]",
    description: "Max 2 competenze CORE — identità principale dell'agenzia. Slug da tassonomia agency_skills.",
    source: "llm",
    updatePolicy: "always_overwrite",
    verifiedBehavior: V_OW,
    visibility: "pubblico",
    csvV1: "Competenze core",
    csvV2: "services_core",
    notes: "Passa attraverso classifyCompetenze() che dedupa cross-gruppo.",
  },
  {
    key: "competenze_principali",
    label: "Servizi principali",
    category: "Servizi",
    type: "text[]",
    description: "Max 5 competenze offerte attivamente (oltre le core). Slug da agency_skills.",
    source: "llm",
    updatePolicy: "always_overwrite",
    verifiedBehavior: V_OW,
    visibility: "pubblico",
    csvV1: "Competenze principali",
    csvV2: "services_principal",
  },
  {
    key: "altre_competenze",
    label: "Altre competenze",
    category: "Servizi",
    type: "text[]",
    description: "Max 10 competenze complementari citate marginalmente.",
    source: "llm",
    updatePolicy: "always_overwrite",
    verifiedBehavior: V_OW,
    visibility: "pubblico",
    csvV1: "Altre competenze",
    csvV2: "services_other",
  },
  {
    key: "caratteristiche",
    label: "Caratteristiche",
    category: "Servizi",
    type: "text[]",
    description: "Caratteristiche distintive (es. 'remote-first', 'b-corp'). Max 12.",
    source: "llm",
    updatePolicy: "fill_if_empty",
    verifiedBehavior: V_FILL,
    visibility: "pubblico",
    csvV1: "Caratteristiche",
    csvV2: "attributes",
  },
  {
    key: "deliverables",
    label: "Deliverables",
    category: "Servizi",
    type: "text[]",
    description: "Output/prodotti concreti dichiarati (es. 'sito-web', 'brand-identity'). Max 10, slug kebab-case.",
    source: "llm",
    updatePolicy: "fill_if_empty",
    verifiedBehavior: V_FILL,
    visibility: "pubblico",
    csvV1: "Deliverables",
    csvV2: "deliverables",
  },
  {
    key: "platforms_tech",
    label: "Platforms & tech",
    category: "Servizi",
    type: "text[]",
    description: "Piattaforme/tecnologie dichiarate (es. 'wordpress', 'shopify', 'meta-ads'). Max 12.",
    source: "llm",
    updatePolicy: "fill_if_empty",
    verifiedBehavior: V_FILL,
    visibility: "pubblico",
    csvV1: "Platforms tech",
    csvV2: "platforms_tech",
  },
  {
    key: "pillar_primario_slug",
    label: "Pillar primario",
    category: "SEO",
    type: "text",
    description: "Slug pillar principale per SEO/tassonomia. Manuale.",
    source: "manual",
    updatePolicy: "manual_only",
    verifiedBehavior: V_NEVER,
    visibility: "interno",
    csvV1: "Pillar primario (slug)",
  },

  // ============================================================
  // CLIENTI & FIT
  // ============================================================
  {
    key: "industries",
    label: "Industries",
    category: "Clienti & fit",
    type: "text[]",
    description: "Settori clienti serviti con esperienza dimostrata. Max 8, slug kebab-case.",
    source: "llm",
    updatePolicy: "fill_if_empty",
    verifiedBehavior: V_FILL,
    visibility: "pubblico",
    csvV1: "Industries",
    csvV2: "industries",
  },
  {
    key: "audiences",
    label: "Audiences",
    category: "Clienti & fit",
    type: "text[]",
    description: "Mercato di riferimento. Enum stretto: b2b, b2c, b2g, nonprofit.",
    source: "llm",
    updatePolicy: "fill_if_empty",
    verifiedBehavior: V_FILL,
    visibility: "pubblico",
    csvV1: "Audiences",
    csvV2: "audiences",
  },
  {
    key: "ideal_client_sizes",
    label: "Ideal client sizes",
    category: "Clienti & fit",
    type: "text[]",
    description: "Dimensioni cliente ideale. Enum: startup, smb, mid-market, enterprise.",
    source: "llm",
    updatePolicy: "fill_if_empty",
    verifiedBehavior: V_FILL,
    visibility: "pubblico",
    csvV1: "Ideal client sizes",
    csvV2: "ideal_client_sizes",
  },
  {
    key: "engagement_models",
    label: "Engagement models",
    category: "Clienti & fit",
    type: "text[]",
    description: "Modelli di ingaggio. Enum: project, retainer, consulting, performance, outsourcing.",
    source: "llm",
    updatePolicy: "fill_if_empty",
    verifiedBehavior: V_FILL,
    visibility: "pubblico",
    csvV1: "Engagement models",
    csvV2: "engagement_models",
  },
  {
    key: "lingue",
    label: "Lingue",
    category: "Clienti & fit",
    type: "text[]",
    description: "Lingue di lavoro (es. ['italiano', 'inglese']).",
    source: "llm",
    updatePolicy: "fill_if_empty",
    verifiedBehavior: V_FILL,
    visibility: "pubblico",
    csvV1: "Lingue",
    csvV2: "languages",
  },
  {
    key: "dimensione_team",
    label: "Dimensione team",
    category: "Clienti & fit",
    type: "text",
    description: "Range dipendenti dichiarato: '1-5', '5-10', '10-25', '25-50', '50+'.",
    source: "llm",
    updatePolicy: "fill_if_empty",
    verifiedBehavior: V_FILL,
    visibility: "pubblico",
    csvV1: "Dimensione team",
    csvV2: "team_size_range",
  },

  // ============================================================
  // PRICING
  // ============================================================
  {
    key: "fascia_di_prezzo",
    label: "Fascia di prezzo",
    category: "Pricing",
    type: "text",
    description: "Fascia €/€€/€€€ (indicatore qualitativo legacy).",
    source: "llm",
    updatePolicy: "fill_if_empty",
    verifiedBehavior: V_FILL,
    visibility: "pubblico",
    csvV1: "Fascia di prezzo",
    csvV2: "pricing_range",
  },
  {
    key: "min_project_budget",
    label: "Min project budget",
    category: "Pricing",
    type: "int",
    description: "Budget minimo dichiarato per un progetto (numero intero).",
    source: "llm",
    updatePolicy: "fill_if_empty",
    verifiedBehavior: V_FILL,
    visibility: "pubblico",
    csvV1: "Min project budget",
    csvV2: "min_project_budget",
  },
  {
    key: "min_project_currency",
    label: "Currency",
    category: "Pricing",
    type: "text",
    description: "Codice ISO 4217 (default EUR).",
    source: "llm",
    updatePolicy: "fill_if_empty",
    verifiedBehavior: V_FILL,
    visibility: "pubblico",
    csvV1: "Min project currency",
    csvV2: "min_project_currency",
  },
  {
    key: "typical_project_min",
    label: "Typical project min",
    category: "Pricing",
    type: "int",
    description: "Estremo inferiore range progetti tipici.",
    source: "llm",
    updatePolicy: "fill_if_empty",
    verifiedBehavior: V_FILL,
    visibility: "pubblico",
    csvV1: "Typical project min",
    csvV2: "typical_project_min",
  },
  {
    key: "typical_project_max",
    label: "Typical project max",
    category: "Pricing",
    type: "int",
    description: "Estremo superiore range progetti tipici.",
    source: "llm",
    updatePolicy: "fill_if_empty",
    verifiedBehavior: V_FILL,
    visibility: "pubblico",
    csvV1: "Typical project max",
    csvV2: "typical_project_max",
  },
  {
    key: "pricing_models",
    label: "Pricing models",
    category: "Pricing",
    type: "text[]",
    description: "Modelli economici. Enum: fee, hourly, performance, media-commission, mixed.",
    source: "llm",
    updatePolicy: "fill_if_empty",
    verifiedBehavior: V_FILL,
    visibility: "pubblico",
    csvV1: "Pricing models",
    csvV2: "pricing_models",
  },

  // ============================================================
  // CONTENUTI EDITORIALI
  // ============================================================
  {
    key: "descrizione_breve",
    label: "Descrizione breve",
    category: "Contenuti",
    type: "text",
    description: "Payoff SEO 140-180 char. Sempre sovrascritto dall'LLM (obiettivo: qualità uniforme).",
    source: "llm",
    updatePolicy: "always_overwrite",
    verifiedBehavior: V_OW,
    visibility: "pubblico",
    csvV1: "Descrizione breve",
    csvV2: "editorial_short",
  },
  {
    key: "content",
    label: "Descrizione lunga",
    category: "Contenuti",
    type: "text",
    description: "Descrizione lunga 600-1200 char, 3-5 paragrafi. Sempre sovrascritta dall'LLM.",
    source: "llm",
    updatePolicy: "always_overwrite",
    verifiedBehavior: V_OW,
    visibility: "pubblico",
    csvV1: "Content",
    csvV2: "editorial_long",
  },
  {
    key: "differentiators",
    label: "Differentiators",
    category: "Contenuti",
    type: "jsonb",
    description: "Array elementi distintivi con evidenza. Max 5. Frasi concise, no marketing vuoto.",
    source: "llm",
    updatePolicy: "fill_if_empty",
    verifiedBehavior: V_FILL,
    visibility: "pubblico",
    csvV1: "Differentiators JSON",
    csvV2: "differentiators_json",
  },
  {
    key: "declared_methodology",
    label: "Declared methodology",
    category: "Contenuti",
    type: "text",
    description: "Nome + descrizione breve (100-300 char) del metodo proprietario dichiarato.",
    source: "llm",
    updatePolicy: "fill_if_empty",
    verifiedBehavior: V_FILL,
    visibility: "pubblico",
    csvV1: "Declared methodology",
    csvV2: "declared_methodology",
  },
  {
    key: "faq",
    label: "FAQ",
    category: "Contenuti",
    type: "jsonb",
    description: "Array {q, a} di domande/risposte presenti sul sito. Max 8.",
    source: "llm",
    updatePolicy: "fill_if_empty",
    verifiedBehavior: V_FILL,
    visibility: "pubblico",
    csvV1: "FAQ JSON",
    csvV2: "faq_json",
  },
  {
    key: "best_for",
    label: "Best for",
    category: "Valutazione",
    type: "jsonb",
    description: "Casi/clienti per cui l'agenzia è particolarmente adatta (con evidenze).",
    source: "manual",
    updatePolicy: "manual_only",
    verifiedBehavior: V_NEVER,
    visibility: "pubblico",
    csvV1: "Best for JSON",
    csvV2: "best_for_json",
    notes: "Popolato in futuro dall'agente 'evaluation'.",
  },
  {
    key: "less_suitable_for",
    label: "Less suitable for",
    category: "Valutazione",
    type: "jsonb",
    description: "Casi per cui il fit è debole/non dimostrato.",
    source: "manual",
    updatePolicy: "manual_only",
    verifiedBehavior: V_NEVER,
    visibility: "pubblico",
    csvV1: "Less suitable for JSON",
    csvV2: "less_suitable_for_json",
    notes: "Popolato in futuro dall'agente 'evaluation'.",
  },

  // ============================================================
  // RECENSIONI
  // ============================================================
  {
    key: "google_rating",
    label: "Google rating",
    category: "Recensioni",
    type: "numeric",
    description: "Rating aggregato Google Places (0.0-5.0).",
    source: "google_places",
    updatePolicy: "always_overwrite",
    verifiedBehavior: V_OW,
    visibility: "pubblico",
    csvV1: "Google rating",
    csvV2: "google_rating",
  },
  {
    key: "google_recensioni_count",
    label: "N. recensioni Google",
    category: "Recensioni",
    type: "int",
    description: "Numero totale recensioni Google.",
    source: "google_places",
    updatePolicy: "always_overwrite",
    verifiedBehavior: V_OW,
    visibility: "pubblico",
    csvV1: "N. recensioni Google",
    csvV2: "google_review_count",
  },
  {
    key: "google_place_id",
    label: "Google Place ID",
    category: "Recensioni",
    type: "text",
    description: "External ID Google Places. Chiave per il collegamento reviews.",
    source: "google_places",
    updatePolicy: "always_overwrite",
    verifiedBehavior: V_OW,
    visibility: "interno",
    csvV1: "Google Place ID",
    csvV2: "google_place_id",
  },
  {
    key: "google_categoria",
    label: "Categoria Google",
    category: "Recensioni",
    type: "text",
    description: "Categoria tipo POI restituita da Google Places.",
    source: "google_places",
    updatePolicy: "always_overwrite",
    verifiedBehavior: V_OW,
    visibility: "pubblico",
    csvV1: "Categoria Google",
  },
  {
    key: "google_foto_url",
    label: "Foto Google",
    category: "Recensioni",
    type: "text",
    description: "Path prima foto Google Places (formato 'places/{id}/photos/{ref}').",
    source: "google_places",
    updatePolicy: "always_overwrite",
    verifiedBehavior: V_OW,
    visibility: "pubblico",
    csvV1: "Foto Google (URL)",
  },
  {
    key: "match_confidence",
    label: "Match confidence",
    category: "Recensioni",
    type: "numeric",
    description: "Confidenza del match Google Places (0-1). 1.0 = domain match, 0.9+ = name match stringente.",
    source: "computed",
    updatePolicy: "always_overwrite",
    verifiedBehavior: V_OW,
    visibility: "interno",
    csvV1: "Match confidence",
  },
  {
    key: "review_summary",
    label: "Review summary",
    category: "Recensioni",
    type: "text",
    description: "Sintesi neutrale delle recensioni analizzate.",
    source: "manual",
    updatePolicy: "manual_only",
    verifiedBehavior: V_NEVER,
    visibility: "pubblico",
    csvV1: "Review summary",
    csvV2: "review_summary",
    notes: "Popolato in futuro dall'agente 'review-enrichment'.",
  },
  {
    key: "review_strengths",
    label: "Review strengths",
    category: "Recensioni",
    type: "jsonb",
    description: "Temi positivi ricorrenti nelle recensioni (>=2 evidenze).",
    source: "manual",
    updatePolicy: "manual_only",
    verifiedBehavior: V_NEVER,
    visibility: "pubblico",
    csvV1: "Review strengths JSON",
    csvV2: "review_strengths_json",
    notes: "Popolato in futuro dall'agente 'review-enrichment'.",
  },
  {
    key: "review_criticisms",
    label: "Review criticisms",
    category: "Recensioni",
    type: "jsonb",
    description: "Criticità ricorrenti (>=2 evidenze). Accuse gravi richiedono revisione umana.",
    source: "manual",
    updatePolicy: "manual_only",
    verifiedBehavior: V_NEVER,
    visibility: "pubblico",
    csvV1: "Review criticisms JSON",
    csvV2: "review_criticisms_json",
  },
  {
    key: "review_analyzed_count",
    label: "Review analyzed count",
    category: "Recensioni",
    type: "int",
    description: "Numero recensioni realmente analizzate per la sintesi. Distinto dal totale.",
    source: "manual",
    updatePolicy: "manual_only",
    verifiedBehavior: V_NEVER,
    visibility: "pubblico",
    csvV1: "Review analyzed count",
    csvV2: "review_analyzed_count",
  },
  {
    key: "review_analysis_confidence",
    label: "Review analysis confidence",
    category: "Recensioni",
    type: "text",
    description: "Affidabilità della sintesi review: insufficient, low, medium, high.",
    source: "manual",
    updatePolicy: "manual_only",
    verifiedBehavior: V_NEVER,
    visibility: "pubblico",
    csvV1: "Review analysis confidence",
    csvV2: "review_analysis_confidence",
  },
  {
    key: "review_snapshot_date",
    label: "Review snapshot date",
    category: "Recensioni",
    type: "date",
    description: "Data ultimo snapshot recensioni.",
    source: "manual",
    updatePolicy: "manual_only",
    verifiedBehavior: V_NEVER,
    visibility: "pubblico",
    csvV1: "Review snapshot date",
    csvV2: "google_snapshot_date",
  },

  // ============================================================
  // VALUTAZIONE EDITORIALE
  // ============================================================
  {
    key: "editorial_summary",
    label: "Editorial summary",
    category: "Valutazione",
    type: "text",
    description: "Lettura sintetica motivata dell'agenzia. Da agente evaluation (futuro).",
    source: "manual",
    updatePolicy: "manual_only",
    verifiedBehavior: V_NEVER,
    visibility: "pubblico",
    csvV1: "Editorial summary",
    csvV2: "editorial_summary",
  },
  {
    key: "eval_strengths",
    label: "Eval strengths",
    category: "Valutazione",
    type: "jsonb",
    description: "Punti di forza con evidenze (rinvio a evidence IDs). Da agente evaluation.",
    source: "manual",
    updatePolicy: "manual_only",
    verifiedBehavior: V_NEVER,
    visibility: "pubblico",
    csvV1: "Eval strengths JSON",
    csvV2: "eval_strengths_json",
  },
  {
    key: "eval_limitations",
    label: "Eval limitations",
    category: "Valutazione",
    type: "jsonb",
    description: "Limiti evidenze o fit debole (non giudizi gratuiti). Da agente evaluation.",
    source: "manual",
    updatePolicy: "manual_only",
    verifiedBehavior: V_NEVER,
    visibility: "pubblico",
    csvV1: "Eval limitations JSON",
    csvV2: "eval_limitations_json",
  },
  {
    key: "evidence_grade",
    label: "Evidence grade",
    category: "Valutazione",
    type: "text",
    description: "Grado di completezza delle prove disponibili. Enum.",
    source: "manual",
    updatePolicy: "manual_only",
    verifiedBehavior: V_NEVER,
    visibility: "pubblico",
    csvV1: "Evidence grade",
    csvV2: "evidence_grade",
  },
  {
    key: "evaluation_confidence",
    label: "Evaluation confidence",
    category: "Valutazione",
    type: "text",
    description: "Affidabilità della valutazione complessiva. Enum.",
    source: "manual",
    updatePolicy: "manual_only",
    verifiedBehavior: V_NEVER,
    visibility: "pubblico",
    csvV1: "Evaluation confidence",
    csvV2: "evaluation_confidence",
  },
  {
    key: "human_reviewed",
    label: "Human reviewed",
    category: "Valutazione",
    type: "boolean",
    description: "Flag: una persona ha revisionato la valutazione. Richiesto per badge 'verificata'.",
    source: "manual",
    updatePolicy: "manual_only",
    verifiedBehavior: V_NEVER,
    visibility: "pubblico",
    csvV1: "Human reviewed",
    csvV2: "human_reviewed",
  },

  // ============================================================
  // FINANCIAL (per anno)
  // ============================================================
  ...([2024, 2025, 2026] as const).flatMap<FieldDefinition>((y) => [
    {
      key: `revenue_${y}`,
      label: `Ricavi ${y}`,
      category: "Financial",
      type: "numeric",
      description: `Fatturato ${y} in EUR.`,
      source: "partner",
      updatePolicy: "manual_only",
      verifiedBehavior: V_NEVER,
      visibility: "pubblico",
      csvV1: `Revenue ${y}`,
      csvV2: `revenue_${y}`,
    },
    {
      key: `employees_${y}`,
      label: `Dipendenti ${y}`,
      category: "Financial",
      type: "int",
      description: `Numero dipendenti riferito al ${y}.`,
      source: "partner",
      updatePolicy: "manual_only",
      verifiedBehavior: V_NEVER,
      visibility: "pubblico",
      csvV1: `Employees ${y}`,
      csvV2: `employees_${y}`,
    },
    {
      key: `ebitda_${y}`,
      label: `EBITDA ${y}`,
      category: "Financial",
      type: "numeric",
      description: `EBITDA riclassificato ${y}.`,
      source: "partner",
      updatePolicy: "manual_only",
      verifiedBehavior: V_NEVER,
      visibility: "pubblico_opzionale",
      csvV1: `EBITDA ${y}`,
      csvV2: `ebitda_${y}`,
    },
  ]),

  // ============================================================
  // SEO
  // ============================================================
  {
    key: "seo_title",
    label: "SEO title",
    category: "SEO",
    type: "text",
    description: "Override manuale SEO title. Se null, WP genera dallo slug.",
    source: "manual",
    updatePolicy: "manual_only",
    verifiedBehavior: V_NEVER,
    visibility: "pubblico",
    csvV1: "SEO title",
    csvV2: "seo_title",
  },
  {
    key: "meta_description",
    label: "Meta description",
    category: "SEO",
    type: "text",
    description: "Override manuale meta description SERP.",
    source: "manual",
    updatePolicy: "manual_only",
    verifiedBehavior: V_NEVER,
    visibility: "pubblico",
    csvV1: "Meta description",
    csvV2: "meta_description",
  },
  {
    key: "serp_position",
    label: "SERP position (miglioreagenzia.it)",
    category: "SEO",
    type: "int",
    description:
      "Posizione top-100 in cui miglioreagenzia.it appare cercando '{nome agenzia} {città}' su Google IT. NULL = fuori top 100.",
    source: "computed",
    updatePolicy: "always_overwrite",
    verifiedBehavior: "Ricalcolato ad ogni run dell'agente serp-position.",
    visibility: "interno",
    csvV1: "SERP position",
    notes: "Popolato dall'agente agency-serp-position (weekly). Solo agenzie con publish_status='publish'.",
  },
  {
    key: "serp_query",
    label: "SERP query usata",
    category: "SEO",
    type: "text",
    description: "Query esatta usata su Google (nome + città capitalizzata).",
    source: "computed",
    updatePolicy: "always_overwrite",
    verifiedBehavior: "Ricalcolato ad ogni run dell'agente serp-position.",
    visibility: "interno",
    csvV1: "SERP query",
  },
  {
    key: "serp_url",
    label: "SERP URL rankata",
    category: "SEO",
    type: "text",
    description: "URL specifica di miglioreagenzia.it che appare in SERP per quella query. Utile per QA (giusta pagina o listing?).",
    source: "computed",
    updatePolicy: "always_overwrite",
    verifiedBehavior: V_SYSTEM,
    visibility: "interno",
    csvV1: "SERP url",
  },
  {
    key: "serp_checked_at",
    label: "SERP checked at",
    category: "SEO",
    type: "timestamptz",
    description: "Timestamp ultimo run agent serp-position su questa agenzia.",
    source: "computed",
    updatePolicy: "always_overwrite",
    verifiedBehavior: V_SYSTEM,
    visibility: "interno",
    csvV1: "SERP checked at",
  },
  {
    key: "indexation_status",
    label: "Indexation status",
    category: "SEO",
    type: "text",
    description: "Gate di indicizzazione: noindex (default), eligible, index.",
    source: "manual",
    updatePolicy: "manual_only",
    verifiedBehavior: V_NEVER,
    visibility: "interno",
    csvV1: "Indexation status",
    csvV2: "indexation_status",
    notes: "Default noindex. Deve superare quality gate per essere 'index'.",
  },

  // ============================================================
  // WORKFLOW
  // ============================================================
  {
    key: "verifica",
    label: "Verifica",
    category: "Workflow",
    type: "text",
    description: "Stato rivendicazione/verifica: verified | to-review | pending. Manuale.",
    source: "manual",
    updatePolicy: "manual_only",
    verifiedBehavior: "Il valore stesso — non toccato dagli agenti.",
    visibility: "pubblico",
    csvV1: "Verifica",
    csvV2: "claim_status",
  },
  {
    key: "status_curatela",
    label: "Status curatela",
    category: "Workflow",
    type: "text",
    description: "Maturità curatoriale: proposta, verificata, rifiutata.",
    source: "manual",
    updatePolicy: "manual_only",
    verifiedBehavior: V_NEVER,
    visibility: "interno",
    csvV1: "Status curatela",
    csvV2: "curation_status",
  },
  {
    key: "publish_status",
    label: "Publication status",
    category: "Workflow",
    type: "text",
    description: "Stato editoriale WP: draft, publish, pending, trash.",
    source: "manual",
    updatePolicy: "manual_only",
    verifiedBehavior: V_NEVER,
    visibility: "interno",
    csvV1: "Status pubblicazione",
    csvV2: "publication_status",
  },
  {
    key: "note_curatore",
    label: "Note curatore",
    category: "Workflow",
    type: "text",
    description: "Note interne editoriali. Non pubblicate.",
    source: "manual",
    updatePolicy: "manual_only",
    verifiedBehavior: V_NEVER,
    visibility: "interno",
    csvV1: "Note curatore",
    csvV2: "curator_notes",
  },
  {
    key: "last_verified_at",
    label: "Last verified at",
    category: "Workflow",
    type: "timestamptz",
    description: "Data ultima verifica editoriale umana.",
    source: "manual",
    updatePolicy: "manual_only",
    verifiedBehavior: V_NEVER,
    visibility: "pubblico",
    csvV1: "Last verified at",
    csvV2: "last_verified_at",
  },
  {
    key: "quality_gate_score",
    label: "Quality gate score",
    category: "Workflow",
    type: "numeric",
    description: "Punteggio di completezza per decidere l'indicizzabilità.",
    source: "computed",
    updatePolicy: "manual_only",
    verifiedBehavior: V_NEVER,
    visibility: "interno",
    csvV1: "Quality gate score",
    csvV2: "quality_gate_score",
    notes: "Logica di calcolo non ancora implementata.",
  },

  // ============================================================
  // ENRICHMENT TRACKING
  // ============================================================
  {
    key: "last_enriched_at",
    label: "Last enriched at",
    category: "Enrichment tracking",
    type: "timestamptz",
    description: "Timestamp ultimo run dell'agency-updater su questa agenzia.",
    source: "computed",
    updatePolicy: "always_overwrite",
    verifiedBehavior: V_SYSTEM,
    visibility: "interno",
    csvV2: "last_enriched_at",
  },
  {
    key: "enrichment_status",
    label: "Enrichment status",
    category: "Enrichment tracking",
    type: "text",
    description: "Esito ultimo run: success, partial, error.",
    source: "computed",
    updatePolicy: "always_overwrite",
    verifiedBehavior: V_SYSTEM,
    visibility: "interno",
  },
  {
    key: "enrichment_errors",
    label: "Enrichment errors",
    category: "Enrichment tracking",
    type: "jsonb",
    description: "Errori per source dell'ultimo run (google_places / website_scrape / llm).",
    source: "computed",
    updatePolicy: "always_overwrite",
    verifiedBehavior: V_SYSTEM,
    visibility: "interno",
  },
  {
    key: "sources_used",
    label: "Sources used",
    category: "Enrichment tracking",
    type: "jsonb",
    description: "Flag booleani { google_places, website_scrape, llm } dell'ultimo run.",
    source: "computed",
    updatePolicy: "always_overwrite",
    verifiedBehavior: V_SYSTEM,
    visibility: "interno",
  },
  {
    key: "visual_enrichment_status",
    label: "Visual enrichment status",
    category: "Enrichment tracking",
    type: "text",
    description: "Esito ultimo run agent visual: success, partial, error.",
    source: "visual_agent",
    updatePolicy: "always_overwrite",
    verifiedBehavior: V_SYSTEM,
    visibility: "interno",
  },
  {
    key: "visual_enriched_at",
    label: "Visual enriched at",
    category: "Enrichment tracking",
    type: "timestamptz",
    description: "Timestamp ultimo run agent visual.",
    source: "visual_agent",
    updatePolicy: "always_overwrite",
    verifiedBehavior: V_SYSTEM,
    visibility: "interno",
  },

  // ============================================================
  // SISTEMA
  // ============================================================
  {
    key: "domain_id",
    label: "Domain ID",
    category: "Sistema",
    type: "uuid",
    description: "FK a network_domains: tenant di appartenenza dell'agenzia.",
    source: "creation",
    updatePolicy: "on_creation",
    verifiedBehavior: V_NEVER,
    visibility: "interno",
  },
  {
    key: "created_at",
    label: "Created at",
    category: "Sistema",
    type: "timestamptz",
    description: "Timestamp creazione record.",
    source: "system",
    updatePolicy: "on_creation",
    verifiedBehavior: V_NEVER,
    visibility: "interno",
  },
  {
    key: "updated_at",
    label: "Updated at",
    category: "Sistema",
    type: "timestamptz",
    description: "Timestamp ultima modifica (trigger automatico).",
    source: "system",
    updatePolicy: "always_overwrite",
    verifiedBehavior: V_SYSTEM,
    visibility: "interno",
  },
];
