ALTER TABLE agencies
  ADD COLUMN IF NOT EXISTS lat DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS lng DOUBLE PRECISION;

CREATE INDEX IF NOT EXISTS idx_agencies_coordinates ON agencies (domain_id) WHERE lat IS NOT NULL AND lng IS NOT NULL;
